cypress_compass_elephant:
    compass_binary_path: "/usr/local/bin/compass"
    compass_projects:
        main:
            path: %kernel.root_dir%/../src/Cypress/GitElephantHostBundle/Resources/public/compass