cypress_git_elephant_host:
    login_url: https://github.com/login/oauth/authorize
    access_token_url: https://github.com/login/oauth/access_token
    client_id: 1787baab061073db8084
    client_secret: 8d8edbfe969165285ea3fdc2a35f0c743433f9cb