stof_doctrine_extensions:
#    mongodb:
#        default:
#            sluggable: true
#            timestampable: true
    orm:
        default:
            sluggable: true
            timestampable: true