imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    #- { resource: bundles/mongo.yml }
    - { resource: bundles/doctrine_ext.yml }
    - { resource: bundles/ornicar_gravatar.yml }
    #- { resource: bundles/less_elephant.yml }
    - { resource: bundles/compass_elephant.yml }

framework:
    #esi:             ~
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: "%kernel.debug%"
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trust_proxy_headers: false # Whether or not the Request object should trust proxy headers (X_FORWARDED_FOR/HTTP_CLIENT_IP)
    session:         ~
    trusted_proxies: ~

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ CypressGitElephantHostBundle, OryzoneBoilerplateBundle ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        uglifyjs: ~
        uglifycss: ~
    assets:
        main_js:
            inputs:
                - bundles/cypressgitelephanthost/components/jquery/jquery.js
                - bundles/cypressgitelephanthost/compass/javascripts/bootstrap-dropdown.js
                - bundles/cypressgitelephanthost/js/md5.js
            filters: [?uglifyjs]
        home_js:
            inputs:
                - bundles/cypressgitelephanthost/components/spin.js/spin.js
                - bundles/cypressgitelephanthost/js/spinner_options.js
                - bundles/cypressgitelephanthost/js/spin.jquery.js
                - bundles/cypressgitelephanthost/js/homepage.js
            filters: [?uglifyjs]
        repository_js:
            inputs:
                - bundles/cypressgitelephanthost/components/underscore/underscore.js
                - bundles/cypressgitelephanthost/components/backbone/backbone.js
                - bundles/cypressgitelephanthost/components/spin.js/spin.js
                - bundles/cypressgitelephanthost/js/spinner_options.js
                - bundles/cypressgitelephanthost/js/spin.jquery.js
                - bundles/cypressgitelephanthost/js/bb/CommitModel.js
                - bundles/cypressgitelephanthost/js/bb/CommitCollection.js
                - bundles/cypressgitelephanthost/js/bb/RepositoryView.js
                - bundles/cypressgitelephanthost/js/bb/BreadcrumbView.js
                - bundles/cypressgitelephanthost/js/bb/Router.js
                - bundles/cypressgitelephanthost/js/bb/Main.js
            filters: [?uglifyjs]
        github_repositories:
            inputs:
                - bundles/cypressgitelephanthost/components/underscore/underscore.js
                - bundles/cypressgitelephanthost/components/backbone/backbone.js
                - bundles/cypressgitelephanthost/components/spin.js/spin.js
                - bundles/cypressgitelephanthost/js/spinner_options.js
                - bundles/cypressgitelephanthost/js/spin.jquery.js
                - bundles/cypressgitelephanthost/js/bb_github_repositories/GithubRepositoryModel.js
                - bundles/cypressgitelephanthost/js/bb_github_repositories/RepositoryView.js
                - bundles/cypressgitelephanthost/js/bb_github_repositories/PaginationView.js
                - bundles/cypressgitelephanthost/js/bb_github_repositories/UserModel.js
                - bundles/cypressgitelephanthost/js/bb_github_repositories/ApiModel.js
                - bundles/cypressgitelephanthost/js/bb_github_repositories/ListView.js
                - bundles/cypressgitelephanthost/js/bb_github_repositories/AppView.js

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport:  "%mailer_transport%"
    host:       "%mailer_host%"
    username:   "%mailer_user%"
    password:   "%mailer_password%"
    port:       25
    spool:      { type: memory }


jms_di_extra:
    locations:
        all_bundles: false
        bundles: [CypressGitElephantHostBundle]
        directories: ["%kernel.root_dir%/../src"]

cypress_git_elephant_host:
    login_url: https://github.com/login/oauth/authorize
    access_token_url: https://github.com/login/oauth/access_token
    client_id: 1787baab061073db8084
    client_secret: 8d8edbfe969165285ea3fdc2a35f0c743433f9cb
    repositories_dir: %kernel.root_dir%/../repositories

cypress_pygments_elephant:
    file_types:
        twig: html+jinja