imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: bundles/mongo.yml }
    - { resource: bundles/doctrine_ext.yml }

framework:
    #esi:             ~
    #translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: "%kernel.debug%"
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trust_proxy_headers: false # Whether or not the Request object should trust proxy headers (X_FORWARDED_FOR/HTTP_CLIENT_IP)
    session:         ~

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ CypressGitElephantHostBundle, OryzoneBoilerplateBundle ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        uglifyjs: ~
        uglifycss: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"
    assets:
        main_js:
            inputs:
                - bundles/cypressgitelephanthost/components/jquery/jquery.js
                - bundles/cypressgitelephanthost/bootstrap/js/bootstrap-dropdown.js
            filters: [?uglifyjs]
        repository_js:
            inputs:
                - bundles/cypressgitelephanthost/components/underscore/underscore.js
                - bundles/cypressgitelephanthost/components/backbone/backbone.js
                - bundles/cypressgitelephanthost/components/spin.js/spin.js
                - bundles/cypressgitelephanthost/js/spinner_options.js
                - bundles/cypressgitelephanthost/js/spin.jquery.js
                - bundles/cypressgitelephanthost/js/bb/Router.js
                - bundles/cypressgitelephanthost/js/bb/RepositoryView.js
                - bundles/cypressgitelephanthost/js/bb/BreadcrumbView.js
            filters: [?uglifyjs]

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }
